### ISSUE TITLE
IE 8.0.6001.18372: Object doesn`t support this property or method

### ISSUE THREAD

**Issue by ihor-shubin** [kayahr/console-shim#2]
Error at Line:109, Char: 5

**Comment by ihor-shubin** [comment]
8.0.6001.12702 - work fine

**Comment by kayahr** [comment]
Can you give me a hint where to find this specific version? Can't reproduce this problem with current IE8 in Windows 7. Also works fine with IE8-mode of IE9.

**Comment by ihor-shubin** [comment]
http://torwald.ru/wp-content/uploads/2009/06/ie8.exe

**Comment by kayahr** [comment]
Demo runs fine with this IE version on Windows XP. Can you please give me more details what you do to produce this error message? Is it enough to load the console-shim.js? Does it occur when you run the console-shim demo? Does it happen when the developer tools are enabled or disabled or both? Do you have browser extensions installed? If it only happens with your own code then please provide an example which produces this error message.

**Comment by kayahr** [comment]
I'm closing this issue because lack of feedback. Please re-open when problem still occurs with current version of console-shim.
